dist: trusty
sudo: false
language: node_js
node_js:
  - "8"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install codecov -g
  - npm install

cache:
  directories:
    - ./node_modules

script:
  - npm run lint-ci
  - npm run test-thanos -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - npm run build-thanos
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - npm run asbuild
  - npm run buildS3

after_success:
  - codecov

before_deploy: npm version patch

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: npm run deploy-without-build
    skip_cleanup: true
    on:
      tags: false
      branch: master

after_deploy: git push --tags
