dist: trusty
sudo: false
language: node_js
node_js:
- '10'
env:
  global:
  - NODE_OPTIONS=--max_old_space_size=7000
cache:
- npm
addons:
  chrome: stable
install:
- npm ci
- npm install codecov -g
- node -p "v8.getHeapStatistics().total_available_size / (1024 * 1024)"
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test-thanos
      script: npm run test-thanos -- --watch=false --progress=false --browsers=ChromeHeadlessCI
    - stage: test-angular-examples
      script:
        - npm run build-deps
        - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
after_success:
- codecov
before_deploy:
- npm run buildS3
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIARJIXB7N7V2AUUGU2
  secret_access_key:
    secure: co1yOsQGtLcGxMRTvUrLHzpFQmriFIDldfkVBOy5mAWCed6G9J8auVHhMj4yuQbwKHoMeA78lNTGmlPyoOgsj4jXl0/e/DhSZCWyiUzG0oWdQwDJIQ3H0z010kyEIwxL7A7eMJg9ZgjZQyiAg7WVWZ293el5MjKbagX+hMAe22yE5uE5HnJFKMWZGpdyCk4cvtJRtGEwwz3v29rTVxr5dUgodwE2bHgEKxfMkTx/7ID+ZwYEqYQg+xVszNedAVUXH3xt6YuH4do68tUUKnj0zSoYa7mX8dQ4oqDYZGkICITjKY5zBSoTMWSZL7XC/TTS5Gx9AiCZCWYhAkkohO3B8VhRl8FtCnKKP3KUcLjziV41tigBSADws8/CL0SSSWwUOm7ZlBkF920R83M4tH4kI1Z5eMALqdBktffhc8hkTBVLB+zfKmzF58N8LaKeL3sCH90OkWNdGg76fmbvw+KBTdoBrtkBeMD243hSgq6k7t9PBGZS0d23wPdMdCQ4fN80Qwc1KfJ7Ro957gffTBQ/ugnngUgy6wiOEIciTEJw/9NhONYVd6+s6vHm1EyLrXYywJiOJ1RBwkJsDBjcNWIzXpA2zIsGaw0EyPlnUe/366KVlnHapmsEz9dkK2kbPOIJ064W0gHKJJsJ2agynAfumN4L1NudhBNLhRL+mfTkOec=
  bucket: superheroiccoding.de
  local-dir: distS3
  upload-dir: angularExamples
  region: eu-central-1
  acl: public_read
  detect_encoding: true
  default_text_charset: utf-8
  cache_control: max-age=31536000
  on:
    repo: SuperheroicCoding/AngularExamples
    branch: master
    tags: true
