dist: trusty
sudo: false
language: node_js
node_js:
  - "10"
cache: npm
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm ci
  - npm install codecov -g

# before_script: npm run fix-memory-limit

script:
  - npm run lint-ci
  - npm run test-thanos -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - npm run build-thanos
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
  - npm run asbuild
  - node --max_old_space_size=6000 node_modules/@angular/cli/bin/ng build --prod --output-path=distS3 --base-href=https://angularexamples.superheroiccoding.de

after_success:
  - codecov

before_deploy: npm version patch
deploy:
  # deploy prod to the aws environment
  - provider: scripts
    script: npm run deploy-without-build
    skip_cleanup: true
    on:
      tags: false
      branch: master

after_deploy: git push --tags
