dist: trusty
sudo: false
language: node_js
node_js:
- '10'
env:
  global:
  - NODE_OPTIONS=--max_old_space_size=7000
cache:
- npm
addons:
  chrome: stable
install:
- npm ci
- npm install codecov -g
script:
- node -p "v8.getHeapStatistics().total_available_size / (1024 * 1024)"
- npm run lint
- npm run test-thanos -- --watch=false --progress=false --browsers=ChromeHeadlessCI
- npm run build-deps
- npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
- npm run buildS3
after_success:
- codecov
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIARJIXB7N7YBBNYQXY
  secret_access_key:
    secure: JVb8DnhGqOpb5XR2f6/mpBNENj4yHpBLbY4YqIADU7fksMT2PwYyR4WC8TD4ft+3wwqL+MMq5rHy4P0/TJv8L1R+hQ9CkFKf0hVXWAXheEfWoWXm9H1yDXoQ8jpGlvDFjSXc5qPzmph+630DUcqVrcNtOPwxTIks1mbFy9iTuip/TQJluI+qqTNQ1ndcgJWuddqJJ3QI5bR5ETG26gWN76doURWwqwlXidOdC0aPV7ITrTOeAlNMpBK/XYbRetB8XoKfqKLw/sIZrO1/ARdJC2IZ8uUaMihQIDJ+sAF3H3a0/emszGhvfY9ztw981xByS7vN1XaRuVy0XRqztD4Glu55ytTAjhzzLetbPB5GQWanjLaAb5trOVgWrPaJ7Z70+h1B6fcYnqZFvri6zjeoXeeKzspn7e6xNP9lGSdBgYFT8PAcfIaZlefQSgYPUgZ/7h4h0jt/skMcwoZGCGX1F/RutFUJRK9iQnnVUHGy2QtctZdhDrqrwkfGbmH4P6L8evciC+j1a/JzgvFkkH69J7wo2kSCZxi8ytTyoM3j0LobKBjG1Ahqeuc9SLD8KI4UQDBNZoOqNIaR7u3j2BztcZAIVFU6pWXK0rMF8uDIl+Jnkurdb3ravlpE9b7t/P3wfP2mx/XMhH1DqqKqARdbGwZLam21tfMxzGswrUevG/Q=
  bucket: superheroiccoding.de
  acl: public_read
  local_dir: distS3
  upload-dir: angularExamples
  detect_encoding: true
  default_text_charset: utf-8
  cache_control: max-age=31536000
  region: eu-central-1
  on:
    repo: SuperheroicCoding/AngularExamples
    branch: master
    tags: true
