dist: trusty
sudo: false
language: node_js
node_js:
- '10'
env:
  global:
  - NODE_OPTIONS=--max_old_space_size=7000
cache:
- npm
addons:
  chrome: stable
install:
- npm ci
- npm install codecov -g
script:
- node -p "v8.getHeapStatistics().total_available_size / (1024 * 1024)"
- npm run lint
- npm run test-thanos -- --watch=false --progress=false --browsers=ChromeHeadlessCI
- npm run build-deps
- npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
- npm run buildS3
after_success:
- codecov
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIARJIXB7N7YBBNYQXY
  secret_access_key:
    secure: RH9f+E0HnpKZ6IpEytPRMz0bS2wfRIpt0SMpigpJm2G40+CQtzlBRTozoWXDebX1xdTmPQ3XEPRnIivK+iHlwcYVo+kL8mTazA26G5Dt6ek/juvTi98A4kBcVApNy4n2NwR5wEpF351+Q+lZWgF9/yIsLED6tGY1YtonFo23hty4R0a6EuAoQ3Y5Ry4J9xWI8AHokZeWT3wSPDTXdILwirjrvqhYnxDXkaQcnICdgfWI40FvJfRrKSj2JlipdnKU0svYbjU2MH2xeHvvW9MXFxDXwCSenHJrJW9UbTAqq8+FzfKTAiGaL4RGvirIg5lusDT9BUfjwIguTR58TDZ8ztVuw6ndJi0w7MAE51/RfnJjnr1exXGfSR+ciPLJgoMPF7vP6G4cPHhiu+j1KJZEY3oIRBAc4dtTIK4pzjfpJ3OPqJJzB8avxvgENcn+KGiHQOqZuhE/u0m8/RvQsnUcRLUluRavSG4arf3gYyNHPlo4EcdBSZ2eum95I+W3O3HtUZlFjawp4QJBHPk4V8GGggO+/GleY/SbQ+awvh7etfmcFNeLfy661sQVi9HuSwrcuTMXo8+0JLK0UzfGdtpSL+xlaGloN4cS7ZY0UMTMKlBOSAke22A8iFVqfJmAIAmkZGJWeuk/H3NGdlFXHinXf7GEodi7Q6zadMEtXOyS6wk=
  bucket: superheroiccoding.de
  acl: public_read
  local_dir: distS3
  upload-dir: angularExamples
  detect_encoding: true
  default_text_charset: utf-8
  cache_control: max-age=31536000
  region: eu-central-1
  on:
    repo: SuperheroicCoding/AngularExamples
    branch: master
    tags: true
