version: ~> 2.0
dist: trusty
language: node_js
os: linux
node_js:
- '10'
env:
  global:
  - NODE_OPTIONS=--max_old_space_size=7000
cache:
- npm
addons:
  chrome: stable
install:
  - npm ci
  - npm install codecov -g
  - npm i travis-ci-cloudfront-invalidation
  - node -p "v8.getHeapStatistics().total_available_size / (1024 * 1024)"
script:
    - npm run lint
    - npm run test-thanos -- --watch=false --progress=false --browsers=ChromeHeadlessCI
    - npm run build-deps
    - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
after_success: codecov
before_deploy: npm run buildS3
deploy:
   on:
     repo: SuperheroicCoding/AngularExamples
     branch: master
   skip_cleanup: true
   provider: s3
   access_key_id: $AWS_ACCESS_ID
   secret_access_key: $AWS_SECRET_KEY
   bucket: superheroiccoding.de
   local_dir: distS3
   upload_dir: angularExamples
   region: eu-central-1
   acl: public_read
   detect_encoding: true
   default_text_charset: utf-8
   cache_control: max-age=31536000
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master'
